# Generated by Django 2.0.1 on 2018-02-13 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20180207_0141'),
        ('subscriber', '0002_auto_20180207_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
